### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by rmzelle**
Fix typos ("draging", "refernces") and capitalize "google docs".

(typos identified with http://www.internetmarketingninjas.com/online-spell-checker.php)

### CODE REVIEW

**Comment by rmzelle** [comment]
Before you merge this, I also wanted to try my hand at clarifying the introduction at the very top. I'll suggest some changes soon.

**Comment by adam3smith** [comment]
Thanks. lmk when you're done and I'll take a look.

**Comment by rmzelle** [comment]
Will do. Not done yet.

While I have your attention, I was planning to:

* deduplicate the line `Installation will add a Scannable Cite export translator to Zotero and change the RTF Scan option to RTF/ODF Scan.` which you have twice now.
* add brief instructions and links on installing LibreOffice and the Zotero LibreOffice plugin.
* add a link to this repo (or directly to https://github.com/Zotero-ODF-Scan/zotero-odf-scan/blob/gh-pages/index.html) so that people know where the documentation is stored.

**Comment by rmzelle** [comment]
By the way, I find the current font (Lato, font-weight 300) extremely exhausting (at least on my non-retina screen). E.g the lowercase g's are especially light. Could we switch to something a little more defined?

Current 16px Lato, font-weight 300:

image

E.g. 14px Open Sans, font-weight normal:

image

**Comment by adam3smith** [comment]
I'm not sure I have Lato -- for me this looks more like the second image already. I'd assume it's falling back to Helvetica or Arial or so. I'm happy for you to just delete Lato as a body font (and then experiment with font-weight and size). 
OK with the rest, though less sure about the link to the documentation repo -- I'd want that pretty small and clearly labeled as page source so that people don't think there's additional documentation.

**Comment by rmzelle** [comment]
> I'd want that pretty small and clearly labeled as page source so that people don't think there's additional documentation.

I was thinking about making the "Hosted on GitHub Pages" a link to the source.

**Comment by rmzelle** [comment]
http://orderedlist.com/minimal/ has also seen some updates. Not sure if it's worth it to try to go back to markdown, though.

**Comment by adam3smith** [comment]
I think you could just swap out the stylesheets?

**Comment by rmzelle** [comment]
Ah, right. Will give that a try.

By the way, I also noticed quite a few in-line quote tags (e.g. `<q>ODF (to citations)</q>`), which don't seem to receive any special formatting. Not really a problem, but just a FYI. Don't think we need to be careful to keep those. Looks like those pieces of text used to be wrapped in double-quote marks in the old markdown.

**Comment by rmzelle** [comment]
> I'm not sure I have Lato -- for me this looks more like the second image already.

It looks fine on macOS with a retina screen, by the way (with both Firefox and Chrome). The screenshot above (which looks bad) was on Chrome on Windows 7.

**Comment by rmzelle** [comment]
The second section in citation markers is just a visual aid for the user, right? It plays no role in the formatting of the eventual Zotero citation, correct? (I'm talking about the `Smith, (2012)` in `{ | Smith, (2012) | | |zu:2433:WQVBH98K}`)

Also, do you know the rules on the use of spaces for the prefix, suffix, and locator? Is the content of each section trimmed, or are (some) spaces kept? E.g. is `{See | Smith, (2012) |p. 45 | for an example |zu:2433:WQVBH98K}` (from your example) equivalent to `{See| Smith, (2012) |p. 45|for an example|zu:2433:WQVBH98K}`?

**Comment by adam3smith** [comment]
Yes on the first question. I'm not 100% sure on the second -- I think it just write the field exactly as is to the corresponding field into the JSON and then the processor may do some stripping, but I'd have to check the regex or test to be certain. 
E.g., in your example, since the processor applies a numeric property to page numbers-ranges, it doesn't care whether there's a space after the page number or not.

**Comment by rmzelle** [comment]
@adam3smith, do you recall where you got the locator listing from? It doesn't match http://docs.citationstyles.org/en/stable/specification.html#locators or http://citationstylist.org/docs/citeproc-js-csl.html#locator-terms. E.g. "folio" is missing. I also don't understand why there are separate entries for "section" and "Section".

**Comment by rmzelle** [comment]
@adam3smith, apart from the question about the locator labels I'm done. Sorry if I went a little overboard with rewriting the text, but I think things are a little clearer now.

**Comment by rmzelle** [comment]
(and in writing this I encountered a problem during installation [I had to manually download the Scannable Cite translator to my Zotero translators directory], as reported at https://forums.zotero.org/discussion/comment/265421#Comment_265421; not sure if that is a general problem, but there were a few similar reports in the past week)

**Comment by rmzelle** [comment]
@adam3smith, bump. Any chance you can review this (or just accept) this this weekend?

P.S. Frank fixed the Scannable Cite translator installation issue I mentioned in the comment above. See https://github.com/Juris-M/zotero-odf-scan-plugin/issues/1.

**Comment by adam3smith** [comment]
yeah, it's on my shortlist. It's a lot of text to review, in my defense.

**Comment by rmzelle** [comment]
Sure. And I realize the raw diff is rather useless. Since I touched most of the text, I recommend just checking out the branch and opening the HTML file in a browser for a side-by-side comparison with the current version. I also created a Gist with embedded CSS at https://gist.github.com/rmzelle/598c5cb9b0e5879a53e6583b078be649, which you can see rendered at 

https://cdn.rawgit.com/rmzelle/598c5cb9b0e5879a53e6583b078be649/raw/142cb9038711bcaeffe9245e65145434d3d2f299/gistfile1.html

**Comment by rmzelle** [comment]
And it was a lot of text to rewrite, too :stuck_out_tongue_closed_eyes:

**Comment by adam3smith** [comment]
Great, thanks

**Comment by rmzelle** [comment]
Great, and thanks for the corrections.

**Pull request merged**
